"""Generates EXTERNAL_8_PROGRAM_HANDOFF_TO_CHECKER.md from the artifacts committed at 8f70789 (no new analysis).
Also verifies that every file referenced by the program's documents exists and that recorded hashes still match."""
import hashlib
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
BASE = ROOT / "workspace" / "external_strategies"
COMMIT = "8f70789801a2fc02b94f3159ebf3bf1b583d347c"


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def committed_sha(rel: str) -> str | None:
    r = subprocess.run(["git", "show", f"{COMMIT}:{rel}"], cwd=ROOT, capture_output=True)
    return hashlib.sha256(r.stdout).hexdigest() if r.returncode == 0 else None


led = json.loads((ROOT / "data" / "trials_ledger.json").read_text())["entries"]
ext = [e for e in led if e["id"].startswith("EXT8-")]
invalid_markers = [e for e in ext if e["id"].endswith("-INVALIDATED")]
invalid_ids = sorted(e["id"][: -len("-INVALIDATED")] for e in invalid_markers)
valid = [e for e in ext if not e["id"].endswith("-INVALIDATED") and e["id"] not in invalid_ids]
master = json.loads((ROOT / "EXTERNAL_8_STRATEGIES_MASTER_LEDGER.json").read_text())
prereg = json.loads((BASE / "_program" / "PREREG_MANIFEST.json").read_text())
amend = json.loads((BASE / "_program" / "PREREG_AMENDMENT_1.json").read_text())
art = json.loads((BASE / "_program" / "ARTEFACT_HASHES.json").read_text())

# ---- link / completeness check
docs = ["EXTERNAL_8_STRATEGIES_STATE.md", "EXTERNAL_8_STRATEGIES_SOURCE_RECOVERY.md"]
refs = set()
for d in docs:
    for m in re.finditer(r"`([A-Za-z0-9_./*\-]+\.(?:md|json|csv|py))`", (ROOT / d).read_text(encoding="utf-8")):
        refs.add(m.group(1))
missing = []
for r in sorted(refs):
    if "*" in r or "<" in r:
        continue
    cands = [ROOT / r, BASE / r, BASE / "_program" / Path(r).name, ROOT / "tools" / Path(r).name,
             ROOT / "tests" / Path(r).name, BASE / "common" / Path(r).name]
    cands += list(BASE.glob(f"*/{Path(r).name}"))
    if not any(c.exists() for c in cands):
        missing.append(r)
drift = [k for k, v in art.items() if (ROOT / k).exists() and sha(ROOT / k) != v]
not_found = [k for k in art if not (ROOT / k).exists()]
# hashes at the committed snapshot
core_files = ["EXTERNAL_8_STRATEGIES_STATE.md", "EXTERNAL_8_STRATEGIES_SOURCE_RECOVERY.md",
              "EXTERNAL_8_STRATEGIES_MASTER_LEDGER.json", "EXTERNAL_8_STRATEGIES_TEST_MATRIX.csv"]
core = {f: (committed_sha(f), sha(ROOT / f)) for f in core_files}

tx = sorted((BASE / "_source_transcripts").glob("*.json"))
L = []
w = L.append
w("# EXTERNAL 8-STRATEGY PROGRAM — HANDOFF TO CHECKER (Agent 2)\n")
w(f"Generated by `workspace/external_strategies/_program/make_checker_handoff.py` from artifacts committed at `{COMMIT}`.")
w("This is a CHECKER HANDOFF: it restates recorded facts and claims for verification. It adds no new analysis or conclusion.\n")
w("## 0. Completeness / linkage check (automated)")
w(f"- Core documents (sha256 at {COMMIT[:8]} == working tree):")
for f, (a, b) in core.items():
    w(f"  - `{f}` `{a}` {'MATCH' if a == b else 'DIFFERS'}")
w(f"- Files referenced from STATE/SOURCE_RECOVERY that could not be located: {missing if missing else 'none'}")
w(f"- `_program/ARTEFACT_HASHES.json`: {len(art)} files; hash drift since recording: {drift if drift else 'none'}; missing: {not_found if not_found else 'none'}")
w(f"- **Recorded-count correction (for the checker):** `EXTERNAL_8_STRATEGIES_STATE.md` §9 says \"62 valid trials + 4 invalid looks\". "
  f"The ledger shows {len(valid)} valid trials + {len(invalid_ids)} invalidated first-run trials = {len(valid) + len(invalid_ids)} looks "
  f"(+ {len(invalid_markers)} correction markers = {len(ext)} EXT8 entries). The DSR n_trials = {master['n_trials']} counts LOOKS, which is consistent. "
  "The committed STATE text is not edited; this handoff records the correction.")
w("  - Note: `data/fx_histdata/*.parquet` are bulk data (not in git; release `bulk-data-v1`). `data/trials_ledger.json` is append-only and grows after the program, so a drift entry for it alone is expected.\n")
w("## 1. Trial IDs (from `data/trials_ledger.json`)")
w(f"- Valid trials: **{len(valid)}**; invalidated first-run trials: **{len(invalid_ids)}**; correction markers: {len(invalid_markers)}.")
w("\n| valid trial id | dataset_group | window | status | n_trades | recorded verdict |\n|---|---|---|---|---|---|")
for e in valid:
    w(f"| `{e['id']}` | {e['dataset_group']} | {e['data_window']['start']}..{e['data_window']['end']} | {e['window_status']} | {e.get('n_trades')} | {e['verdict']} |")
w("\n| invalidated trial id (verdict void) | marker id | reason |\n|---|---|---|")
for e in invalid_markers:
    w(f"| `{e['id'][: -len('-INVALIDATED')]}` | `{e['id']}` | {e['notes']} |")
w("\n## 2. Preregistration hashes")
w(f"- Frozen before any PnL: `_program/PREREG_MANIFEST.json`, frozen_utc {prereg['frozen_utc']}, aggregate SHA-256 `{prereg['aggregate_sha256']}`")
for k, v in prereg["files"].items():
    w(f"  - `{k}` `{v}`")
w(f"- Post-freeze amendment (BUGFIX, no rule change): `_program/PREREG_AMENDMENT_1.json` ({amend['utc']})")
for k, v in amend["files"].items():
    w(f"  - `{k}` `{v}`")
w("\n## 3. Family A bug-fix provenance")
w("- Defect: A1/A2/A3 (MNQ) and A1 (YM) entries were submitted as harness `stop` orders; for shorts a `stop` entry triggers on price FALLING to the level. 1,436/1,454 A1 fills (98.8%) were on the wrong side of the trigger.")
w("- Evidence and fix: `workspace/external_strategies/_program/BUGFIX_A_ENTRY.md`; fix = resting limit at the trigger; test `test_liquidity_trap_short_fills_only_on_spike_above_internal` (`workspace/external_strategies/common/test_families.py`).")
w("- First-run trials remain in the ledger with correction markers (null controls); corrected reruns carry `_fix1` and are separate trials. Rerun script `workspace/external_strategies/common/rerun_A_fix1.py`.\n")
w("## 4. Datasets and windows")
w("| dataset | window used | status | note |\n|---|---|---|---|")
w("| `data/MNQ_1m.parquet`, `data/ES_1m.parquet` (Databento GLBX continuous) | 2024-07-01..2026-06-30 | REUSED_HOLDOUT | Panama back-adjusted at instrument_id changes; loader asserts no row < 2024-07-01 |")
w("| `data/sierra/YM_continuous_1m_latest_90d.parquet` | 2026-06-24..2026-09-21 | REUSED_HOLDOUT | roll 2026-09-14 00:00 UTC back-adjusted |")
w("| `data/fx_histdata/{EURUSD,GBPUSD,USDJPY,USDCAD,NZDUSD,XAUUSD}_1m_bid.parquet` (HistData, BID) | DEV 2022-01-01..2024-12-31 | DEV (FX_SPOT_HISTDATA) | 2025-01-01..2026-08-31 SEALED, not read |")
w("\n## 5. Cost assumptions (`workspace/external_strategies/common/harness.py` SPECS)")
w("- MNQ: tick 0.25, $2/pt, $1.00 RT (confirmed Lucid table), 1-tick adverse slippage on market/stop entries and stop exits, 1-tick trade-through for limits.")
w("- ES: tick 0.25, $50/pt, $3.50 RT (confirmed). YM: tick 1.0, $5/pt, $3.50 RT (ASSUMPTION).")
w("- FX (ASSUMPTIONS): spread EURUSD 0.3 / GBPUSD 0.6 / USDJPY 0.4 / USDCAD 0.6 / NZDUSD 0.7 pips, XAU $0.20; slippage 0.2 pip / $0.05; commission $7 per lot RT. Sensitivity x1.25/x1.5/x2 and x0 re-simulated.")
w("- Same-bar: stop beats target; no target in the entry minute; entry minute touching the stop = stop-out; pending entry cancelled if the stop trades first.\n")
w("## 6. Source transcript hashes (`workspace/external_strategies/_source_transcripts/`)")
w("| file | sha256 |\n|---|---|")
for p in tx:
    w(f"| `{p.name}` | `{sha(p)}` |")
w(f"| owner zip `trading_strategy_video_reports.zip` | `{sha(ROOT / 'trading_strategy_video_reports.zip') if (ROOT / 'trading_strategy_video_reports.zip').exists() else 'not in tree'}` |")
w("\n## 7. Claimed terminal verdicts (as recorded in `EXTERNAL_8_STRATEGIES_STATE.md` §11 — to be CHECKED, not accepted)")
st = (ROOT / "EXTERNAL_8_STRATEGIES_STATE.md").read_text(encoding="utf-8")
sec = st[st.index("## 11."): st.index("## 12.")]
w(sec.split("\n", 1)[1].strip())
w(f"\nProgram-level claims to verify: surviving candidates = 0; White RC CME p = {master['white_reality_check']['CME']['p']}, "
  f"FX/XAU p = {master['white_reality_check']['FX_XAU']['p']}; empirical SR-trials variance {master['sr_trials_var_empirical']:.4f}; n_trials {master['n_trials']}.")
w("\n## 8. Suggested checker procedure")
w("1. Recompute every hash above (`sha256sum`).")
w("2. `python -m pytest -q workspace/external_strategies/common` (harness + synthetic rule tests).")
w("3. Re-derive any verdict from `*/results/trades_*.csv` + `_program/dev_rows.json` without re-simulation; spot-check 5 trades per family against 1-minute bars (dev data only).")
w("4. Confirm no loader reads CME index rows < 2024-07-01 (`common/harness.py::load_futures` assertion) and that FX 2025-01+ was never read.")
w("5. Confirm the Family A invalidation: in `liquidity_trap/results/trades_A1_k1_spike_nearest_MNQ.csv`, side*(entry − (internal ± 1 tick)) > 2 ticks on ~98.8% of rows; in the `_fix1` file on 0%.")
out = ROOT / "EXTERNAL_8_PROGRAM_HANDOFF_TO_CHECKER.md"
out.write_text("\n".join(L) + "\n", encoding="utf-8")
print(json.dumps({"valid": len(valid), "invalid": len(invalid_ids), "missing_refs": missing, "drift": drift,
                  "not_found": not_found, "core_match": {k: a == b for k, (a, b) in core.items()}}, indent=1))
